### ISSUE TITLE
Failure to encode/decode Injective types

### ISSUE THREAD

**Issue by jtieri** [strangelove-ventures/lens#226]
`lens` is currently choking on Injective types due to the codec types not being wired up correctly in the repo. I tried to follow the same pattern as what we did for Evmos but to no avail. It seems like there is some contention in the `init` functions inside of Injectives SDK that cause issues when we try to work with their custom account/encoding types.

To debug the issue I've been configuring the relayer on the Juno/Injective testnets and attempting to get keys added and a light client created on both chains via the cmd: `rly tx clients juno-injective-testnet -d`

I was debugging the issue in this branch: https://github.com/strangelove-ventures/lens/commits/justin/injective
and then importing this into the main branch of the relayer.

I'm seeing error logs like this after running the command though

```
rly tx clients juno-injective-test -d
panic: ethsecp256k1.PubKey conflicts with 2 other(s). Add it to the priority list for types.PubKey.

goroutine 1 [running]:
github.com/tendermint/go-amino.(*Codec).addCheckConflictsWithConcrete_nolock(0x140011b2850, 0x140011e1560)
	/Users/justintieri/go/pkg/mod/github.com/tendermint/go-amino@v0.16.0/codec.go:683 +0x230
github.com/tendermint/go-amino.(*Codec).RegisterConcrete.func1(0x140011b2850, 0x10474eb78?)
	/Users/justintieri/go/pkg/mod/github.com/tendermint/go-amino@v0.16.0/codec.go:242 +0x60
github.com/tendermint/go-amino.(*Codec).RegisterConcrete(0x1045175a0?, {0x1046dc7e0, 0x14000130d50}, {0x103f806cf, 0x1c}, 0x103000c7c?)
	/Users/justintieri/go/pkg/mod/github.com/tendermint/go-amino@v0.16.0/codec.go:244 +0x148
github.com/cosmos/cosmos-sdk/codec.(*LegacyAmino).RegisterConcrete(...)
	/Users/justintieri/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.46.1/codec/amino.go:183
github.com/strangelove-ventures/lens/client.init.0()
	/Users/justintieri/go/src/github.com/strangelove-ventures/lens/client/keys.go:22 +0xf0
```	

Config details for the relayer:

```
injective:
        type: cosmos
        value:
            key: default
            chain-id: injective-888
            rpc-addr: [https://k8s.testnet.tm.injective.network:443](https://k8s.testnet.tm.injective.network/)
            account-prefix: inj
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.00inj
            min-gas-amount: 0
            debug: false
            timeout: 60s
            output-format: json
            sign-mode: direct
    juno:
        type: cosmos
        value:
            key: default
            chain-id: uni-5
            rpc-addr: [https://juno-testnet-rpc.polkachu.com:443](https://juno-testnet-rpc.polkachu.com/)
            account-prefix: juno
            keyring-backend: test
            gas-adjustment: 1.2
            gas-prices: 0.1ujunox
            min-gas-amount: 1
            debug: false
            timeout: 20s
            output-format: json
            sign-mode: direct
```

They provided a branch that removes the `Seal` call in their SDK but that didn't seem to do the trick https://github.com/strangelove-ventures/lens/pull/205

**Comment by joeabbey** [comment]
fixed by #228
