### ISSUE TITLE
nil pointer dereference if config hasn't been created

### ISSUE THREAD

**Issue by joeabbey** [strangelove-ventures/lens#4]
Remove the `$HOME/.lens` dir and try any command... instead of informing the user that they should run `lens config init` it explodes in spectacular fashion:
```
C:\Users\joeab\src\github.com\strangelove-ventures\lens>lens keys list
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x8 pc=0x12879cf]

goroutine 1 [running]:
github.com/strangelove-ventures/lens/client.(*ChainClient).ListAddresses(0x0)
        C:/Users/joeab/src/github.com/strangelove-ventures/lens/client/keys.go:61 +0x2f
github.com/strangelove-ventures/lens/cmd.keysListCmd.func1(0xc000f2b680, {0x2255488, 0x0, 0x0})
        C:/Users/joeab/src/github.com/strangelove-ventures/lens/cmd/keys.go:175 +0x36
github.com/spf13/cobra.(*Command).execute(0xc000f2b680, {0x2255488, 0x0, 0x0})
        C:/Users/joeab/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000eb5b80)
        C:/Users/joeab/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        C:/Users/joeab/go/pkg/mod/github.com/spf13/cobra@v1.2.1/command.go:902
github.com/strangelove-ventures/lens/cmd.Execute()
        C:/Users/joeab/src/github.com/strangelove-ventures/lens/cmd/root.go:84 +0x38
main.main()
        C:/Users/joeab/src/github.com/strangelove-ventures/lens/main.go:21 +0x17
```

Maybe we could add some EnsureConfigExists() method to always run?

Probably wanna check for nil at the actual site too.

**Comment by jackzampolin** [comment]
Closed by #5
